default:
  tags:
    - k8s

stages:
  - code-quality
  - unit-tests
  - build
  - end2fake
  - deploy


include:
  - local: gitlab/code-quality.yml
  - local: gitlab/unit-tests.yml
  - local: gitlab/build.yml
  - local: gitlab/e2fake.yml
  - local: gitlab/deploy.yml
