default:
  tags:
    - k8s

stages:
  - code-quality
  - unit-tests
  - build
  - e2e-tests
  - deploy

linting:
  stage: code-quality
  image: node:22-alpine
  script:
    - npm i -g pnpm@9.15.2
    - pnpm install --frozen-lockfile
    - pnpm lint

typescript:
  stage: code-quality
  image: node:22-alpine
  script:
    - npm i -g pnpm@9.15.2
    - pnpm install --frozen-lockfile
    - pnpm check

unit-tests:
  stage: unit-tests
  image: node:22-alpine
  script:
    - npm i -g pnpm@9.15.2
    - pnpm install --frozen-lockfile
    - pnpm test

codecept:
  stage: e2e-tests
  image: node:22-alpine
  services:
    - name: $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
      alias: frontend
      variables:
        APP_API_URL: "http://backend:3000"
    - name: git.stamus-networks.com:4567/devel/dev/front-end/scirius-fake:main
      alias: backend
  variables:
    APP_URL: "http://frontend:80"
  script:
    - cd codecept
    - npm install --frozen-lockfile
    - npx codeceptjs run

# Build frontend and expose dist/ as downloadable artifact
build-artifacts:
  stage: build
  image: node:22-slim
  script:
    - corepack enable
    - corepack prepare pnpm@8.15.6 --activate
    - pnpm install --frozen-lockfile
    - pnpm run build --base=/preview/
  artifacts:
    name: "frontend-dist-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
    when: on_success
    expire_in: 1 week
    paths:
      - /dist
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $UPSTREAM_NAME == "nightly_build"

docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  before_script:
    - until docker info; do sleep 1; done
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
      -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  rules:
    - if: $UPSTREAM_NAME != "nightly_build"

stamus-install-archive:
  stage: deploy
  image: kroniak/ssh-client
  needs:
    - build-artifacts
  script:
    # Pass the package to stamus-install
    - echo "$CI_COMMIT_REF_NAME" | grep -q "^stamus-\([0-9.]*\)-" || exit 0
    - export UPGRADE_NO="$(echo "$CI_COMMIT_REF_NAME" | sed -e "s/^stamus-\([0-9.]*\)-.*/\1/")"

    - mkdir /root/.ssh/
    - eval $(ssh-agent -s)
    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh-keyscan -H "$GITLAB_RUNNER" > /root/.ssh/known_hosts
    - ssh gitlab@"$GITLAB_RUNNER" mkdir -p "/home/gitlab/packages/scout/$UPGRADE_NO/tags"
    - scp -r "$CI_PROJECT_DIR/apps" gitlab@"$GITLAB_RUNNER":"/home/gitlab/packages/scout/$UPGRADE_NO/tags"
  rules:
    - if: '$CI_COMMIT_TAG && $CI_PROJECT_NAMESPACE == "devel/dev"'

refresh-app-of-apps:
  stage: deploy
  needs:
    - docker
  variables:
    APP: scout
    ACTION: update
    BRANCH: $CI_COMMIT_BRANCH
    SHA: $CI_COMMIT_SHORT_SHA
    PROJECT: $CI_PROJECT_NAME
    NAMESPACE: $CI_PROJECT_NAMESPACE
    SLUG: $CI_PROJECT_PATH_SLUG
  trigger:
    project: devel/devops/app-of-app
    strategy: depend
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://scout.$CI_COMMIT_BRANCH.$CI_PROJECT_PATH_SLUG.stamus-networks.net
    on_stop: delete-env-from-app-of-apps
  rules:
    - if: $UPSTREAM_NAME != "nightly_build"

delete-env-from-app-of-apps:
  stage: deploy
  variables:
    APP: scout
    ACTION: delete
    BRANCH: $CI_COMMIT_BRANCH
    SHA: $CI_COMMIT_SHORT_SHA
    PROJECT: $CI_PROJECT_NAME
    NAMESPACE: $CI_PROJECT_NAMESPACE
    SLUG: $CI_PROJECT_PATH_SLUG
  trigger:
    project: devel/devops/app-of-app
    strategy: depend
  needs:
    - refresh-app-of-apps
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  rules:
    - if: $UPSTREAM_NAME != "nightly_build"
