FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /code
WORKDIR /code

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --force

ENTRYPOINT [ "bash", "-c" ]
CMD [ "pnpm run dev" ]