export const protoMap: Record<string, string> = {
  Alert: 'Alert',
  Anomaly: 'Anomaly',
  Dcerpc: 'DCE/RPC',
  Dhcp: 'DHCP',
  Dnp3: 'DNP3',
  Dns: 'DNS',
  Enip: 'ENIP',
  Fileinfo: 'File Info',
  Flow: 'Flow',
  Ftp: 'FTP',
  Ftp_Data: 'FTP Data',
  Geneve: 'Geneve',
  Http: 'HTTP',
  Http2: 'HTTP2',
  Ikev2: 'IKEv2',
  Imap: 'IMAP',
  Krb5: 'KRB5',
  Modbus: 'Modbus',
  Mqtt: 'MQTT',
  Msn: 'MSN',
  Netflow: 'Netflow',
  Nfs: 'NFS',
  Ntp: 'NTP',
  Rdp: 'RDP',
  Rfb: 'RFB',
  Sip: 'SIP',
  Smb: 'SMB',
  Smtp: 'SMTP',
  Snmp: 'SNMP',
  Ssh: 'SSH',
  Stamus: 'Stamus',
  Tftp: 'TFTP',
  Tls: 'TLS',
  Vntag: 'VN-Tag',
  Vxlan: 'VXLAN',
};
