export const CONTROL_CHARS: Record<number, { abbr: string; name: string }> = {
  0x00: { abbr: 'NU', name: 'Null' },
  0x01: { abbr: 'SOH', name: 'Start of Heading' },
  0x02: { abbr: 'STX', name: 'Start of Text' },
  0x03: { abbr: 'ETX', name: 'End of Text' },
  0x04: { abbr: 'EOT', name: 'End of Transmission' },
  0x05: { abbr: 'ENQ', name: 'Enquiry' },
  0x06: { abbr: 'ACK', name: 'Acknowledge' },
  0x07: { abbr: 'BEL', name: 'Bell' },
  0x08: { abbr: 'BS', name: 'Backspace' },
  0x09: { abbr: 'HT', name: 'Horizontal Tab' },
  0x0a: { abbr: 'LF', name: 'Line Feed' },
  0x0b: { abbr: 'VT', name: 'Vertical Tab' },
  0x0c: { abbr: 'FF', name: 'Form Feed' },
  0x0d: { abbr: 'CR', name: 'Carriage Return' },
  0x0e: { abbr: 'SO', name: 'Shift Out' },
  0x0f: { abbr: 'SI', name: 'Shift In' },
  0x10: { abbr: 'DLE', name: 'Data Link Escape' },
  0x11: { abbr: 'D1', name: 'Device Control 1' },
  0x12: { abbr: 'D2', name: 'Device Control 2' },
  0x13: { abbr: 'D3', name: 'Device Control 3' },
  0x14: { abbr: 'D4', name: 'Device Control 4' },
  0x15: { abbr: 'NAK', name: 'Negative Acknowledge' },
  0x16: { abbr: 'SYN', name: 'Synchronous Idle' },
  0x17: { abbr: 'ETB', name: 'End of Transmission Block' },
  0x18: { abbr: 'CAN', name: 'Cancel' },
  0x19: { abbr: 'EM', name: 'End of Medium' },
  0x1a: { abbr: 'SUB', name: 'Substitute' },
  0x1b: { abbr: 'ESC', name: 'Escape' },
  0x1c: { abbr: 'FS', name: 'File Separator' },
  0x1d: { abbr: 'GS', name: 'Group Separator' },
  0x1e: { abbr: 'RS', name: 'Record Separator' },
  0x1f: { abbr: 'US', name: 'Unit Separator' },
  0x7f: { abbr: 'DEL', name: 'Delete' },
};
