import { z } from 'zod';

export const sightingEventSchema = z.object({
  host: z.string(),
  tx_id: z.number(),
  stream: z.number(),
  packet_info: z.object({
    linktype: z.number(),
  }),
  hostname_info: z.object({
    tld: z.string(),
    host: z.string(),
    domain_without_tld: z.string(),
    url: z.string(),
    domain: z.string(),
    subdomain: z.string(),
  }),
  proto: z.string(),
  http: z.object({
    status: z.number(),
    http_request_body_printable: z.string(),
    http_method: z.string(),
    length: z.number(),
    http_response_body_printable: z.string(),
    hostname: z.string(),
    response_headers: z.array(
      z.object({
        name: z.string(),
        value: z.string(),
      }),
    ),
    http_content_type: z.string(),
    request_headers: z.array(
      z.object({
        name: z.string(),
        value: z.string(),
      }),
    ),
    url: z.string(),
    server: z.string(),
    protocol: z.string(),
  }),
  net_info: z.object({
    src: z.array(z.string()),
    dest_agg: z.string(),
    dest: z.array(z.string()),
    src_agg: z.string(),
  }),
  alert: z.object({
    gid: z.number(),
    action: z.string(),
    rev: z.number(),
    signature: z.string(),
    category: z.string(),
    source: z.object({
      net_info: z.array(z.string()),
      port: z.number(),
      net_info_agg: z.string(),
      ip: z.string(),
    }),
    signature_id: z.number(),
    lateral: z.string().optional(),
    target: z.object({
      net_info: z.array(z.string()),
      port: z.number(),
      net_info_agg: z.string(),
      ip: z.string(),
    }),
    metadata: z.object({
      provider: z.array(z.string()),
      sightings_key: z.array(z.string()),
      sightings_asset: z.array(z.string()),
      updated_at: z.array(z.string()),
      created_at: z.array(z.string()),
      stamus_classification: z.array(z.string()),
    }),
    severity: z.number(),
  }),
  src_ip: z.string(),
  packet: z.string(),
  tenant: z.number(),
  ether: z.object({}).optional(),
  community_id: z.string(),
  tags: z.array(z.string()),
  type: z.string(),
  logger: z.string(),
  dest_port: z.number(),
  dest_ip: z.string(),
  capture_file: z.string(),
  agent: z.object({
    hostname: z.string(),
    ephemeral_id: z.string(),
    name: z.string(),
    version: z.string(),
    id: z.string(),
    type: z.string(),
  }),
  app_proto: z.string(),
  geoip: z.object({
    ip: z.string(),
    country_code3: z.string(),
    latitude: z.number(),
    country_name: z.string(),
    longitude: z.number(),
    continent_code: z.string(),
    location: z.object({
      lon: z.number(),
      lat: z.number(),
    }),
    coordinate: z.array(z.number()),
    continent: z.object({
      name: z.string(),
      code: z.string(),
      geoname_id: z.number(),
    }),
    country_code2: z.string(),
    registered_country: z.object({
      name: z.string(),
      iso_code: z.string(),
      geoname_id: z.number(),
    }),
    city: z.object({
      geoname_id: z.number(),
      name: z.string(),
    }),
    timezone: z.string(),
    country: z.object({
      name: z.string(),
      iso_code: z.string(),
      geoname_id: z.number(),
    }),
  }),
  alerted: z.boolean(),
  discovery: z.object({
    asset: z.string(),
    asset_net: z.string(),
    asset_role: z.array(z.string()),
    key: z.string(),
    value: z.string(),
  }),
  in_iface: z.string(),
  '@timestamp': z.string(),
  '@version': z.string(),
  log: z.object({
    offset: z.number(),
    file: z.object({
      path: z.string(),
    }),
  }),
  flow_id: z.number(),
  event_type: z.string(),
  timestamp: z.string(),
  input: z.object({
    type: z.string(),
  }),
  payload_printable: z.string(),
  metadata: z.object({
    flowbits: z.array(z.string()),
  }),
  src_port: z.number(),
  flow: z.object({
    bytes_toserver: z.number(),
    bytes_toclient: z.number(),
    start: z.string(),
    dest_ip: z.string(),
    dest_port: z.number(),
    src_ip: z.string(),
    pkts_toserver: z.number(),
    pkts_toclient: z.number(),
    src_port: z.number(),
  }),
  _id: z.string(),
});

export type SightingEvent = z.infer<typeof sightingEventSchema>;
